rpc.server.app-name=provider-1
rpc.server.port=9991
rpc.server.registry=zookeeper
rpc.server.registry-addr=127.0.0.1:2181
rpc.server.transport=netty
rpc.server.rate-limit-enabled=false
rpc.server.rate-limit-type=tokenBucket
rpc.server.rate-limit-permits=100
rpc.server.rate-limit-window-millis=1000
rpc.server.rate-limit-bucket-capacity=100
rpc.server.rate-limit-redis-host=127.0.0.1
rpc.server.rate-limit-redis-port=6379
rpc.server.rate-limit-redis-password=
rpc.server.rate-limit-redis-database=0
rpc.server.rate-limit-redis-timeout-millis=2000
rpc.server.rate-limit-redis-key-prefix=wxy-rpc:rate-limit:
rpc.server.rate-limit-redis-batch-size=100
rpc.server.rate-limit-redis-fallback-to-local=true
rpc.server.rate-limit-redis-fail-open=true
rpc.server.biz-core-pool-size=10
rpc.server.biz-max-pool-size=10
rpc.server.biz-queue-capacity=10000
rpc.server.biz-keep-alive-seconds=60
rpc.server.biz-isolation-enabled=false
# rpc.server.biz-isolation-services[0].service-name=com.wxy.rpc.api.service.HelloService-1.0
# rpc.server.biz-isolation-services[0].core-pool-size=4
# rpc.server.biz-isolation-services[0].max-pool-size=8
# rpc.server.biz-isolation-services[0].queue-capacity=200
# rpc.server.biz-isolation-services[0].keep-alive-seconds=60
# 设置指定包下的日志显示级别 INFO/DEBUG/WARNING/OFF
logging.level.com.wxy.rpc=info
